/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "java_game_2d_action_rpg"
include(":java_2d_game")
include(":java_game_tile_editor")
include("pathfinding_editor")
include("db")
include("data")
project(":data").projectDir = file("data")
project(":db").projectDir   = file("db")