/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

rootProject.name = "java_game_2d_action_rpg"
include(":common")
include(":java_2d_game")
include(":java_game_tile_editor")
include("pathfinding_core")
include("pathfinding_editor")
